#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LibraryDB")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertIssueReturnBook(IssueReturnBook instance);
    partial void UpdateIssueReturnBook(IssueReturnBook instance);
    partial void DeleteIssueReturnBook(IssueReturnBook instance);
    partial void InsertloginTable(loginTable instance);
    partial void UpdateloginTable(loginTable instance);
    partial void DeleteloginTable(loginTable instance);
    partial void InsertNewBook(NewBook instance);
    partial void UpdateNewBook(NewBook instance);
    partial void DeleteNewBook(NewBook instance);
    partial void InsertNewMember(NewMember instance);
    partial void UpdateNewMember(NewMember instance);
    partial void DeleteNewMember(NewMember instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Library_Management_System.Properties.Settings.Default.LibraryDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<IssueReturnBook> IssueReturnBooks
		{
			get
			{
				return this.GetTable<IssueReturnBook>();
			}
		}
		
		public System.Data.Linq.Table<loginTable> loginTables
		{
			get
			{
				return this.GetTable<loginTable>();
			}
		}
		
		public System.Data.Linq.Table<NewBook> NewBooks
		{
			get
			{
				return this.GetTable<NewBook>();
			}
		}
		
		public System.Data.Linq.Table<NewMember> NewMembers
		{
			get
			{
				return this.GetTable<NewMember>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IssueReturnBook")]
	public partial class IssueReturnBook : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _irID;
		
		private int _MemberID;
		
		private int _BookID;
		
		private System.DateTime _Book_Issue_Date;
		
		private System.Nullable<System.DateTime> _Book_Return_Date;
		
		private EntityRef<NewBook> _NewBook;
		
		private EntityRef<NewMember> _NewMember;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnirIDChanging(int value);
    partial void OnirIDChanged();
    partial void OnMemberIDChanging(int value);
    partial void OnMemberIDChanged();
    partial void OnBookIDChanging(int value);
    partial void OnBookIDChanged();
    partial void OnBook_Issue_DateChanging(System.DateTime value);
    partial void OnBook_Issue_DateChanged();
    partial void OnBook_Return_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnBook_Return_DateChanged();
    #endregion
		
		public IssueReturnBook()
		{
			this._NewBook = default(EntityRef<NewBook>);
			this._NewMember = default(EntityRef<NewMember>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_irID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int irID
		{
			get
			{
				return this._irID;
			}
			set
			{
				if ((this._irID != value))
				{
					this.OnirIDChanging(value);
					this.SendPropertyChanging();
					this._irID = value;
					this.SendPropertyChanged("irID");
					this.OnirIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberID", DbType="Int NOT NULL")]
		public int MemberID
		{
			get
			{
				return this._MemberID;
			}
			set
			{
				if ((this._MemberID != value))
				{
					if (this._NewMember.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMemberIDChanging(value);
					this.SendPropertyChanging();
					this._MemberID = value;
					this.SendPropertyChanged("MemberID");
					this.OnMemberIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookID", DbType="Int NOT NULL")]
		public int BookID
		{
			get
			{
				return this._BookID;
			}
			set
			{
				if ((this._BookID != value))
				{
					if (this._NewBook.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBookIDChanging(value);
					this.SendPropertyChanging();
					this._BookID = value;
					this.SendPropertyChanged("BookID");
					this.OnBookIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Book_Issue_Date", DbType="Date NOT NULL")]
		public System.DateTime Book_Issue_Date
		{
			get
			{
				return this._Book_Issue_Date;
			}
			set
			{
				if ((this._Book_Issue_Date != value))
				{
					this.OnBook_Issue_DateChanging(value);
					this.SendPropertyChanging();
					this._Book_Issue_Date = value;
					this.SendPropertyChanged("Book_Issue_Date");
					this.OnBook_Issue_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Book_Return_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Book_Return_Date
		{
			get
			{
				return this._Book_Return_Date;
			}
			set
			{
				if ((this._Book_Return_Date != value))
				{
					this.OnBook_Return_DateChanging(value);
					this.SendPropertyChanging();
					this._Book_Return_Date = value;
					this.SendPropertyChanged("Book_Return_Date");
					this.OnBook_Return_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NewBook_IssueReturnBook", Storage="_NewBook", ThisKey="BookID", OtherKey="bId", IsForeignKey=true)]
		public NewBook NewBook
		{
			get
			{
				return this._NewBook.Entity;
			}
			set
			{
				NewBook previousValue = this._NewBook.Entity;
				if (((previousValue != value) 
							|| (this._NewBook.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NewBook.Entity = null;
						previousValue.IssueReturnBooks.Remove(this);
					}
					this._NewBook.Entity = value;
					if ((value != null))
					{
						value.IssueReturnBooks.Add(this);
						this._BookID = value.bId;
					}
					else
					{
						this._BookID = default(int);
					}
					this.SendPropertyChanged("NewBook");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NewMember_IssueReturnBook", Storage="_NewMember", ThisKey="MemberID", OtherKey="mID", IsForeignKey=true)]
		public NewMember NewMember
		{
			get
			{
				return this._NewMember.Entity;
			}
			set
			{
				NewMember previousValue = this._NewMember.Entity;
				if (((previousValue != value) 
							|| (this._NewMember.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NewMember.Entity = null;
						previousValue.IssueReturnBooks.Remove(this);
					}
					this._NewMember.Entity = value;
					if ((value != null))
					{
						value.IssueReturnBooks.Add(this);
						this._MemberID = value.mID;
					}
					else
					{
						this._MemberID = default(int);
					}
					this.SendPropertyChanged("NewMember");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.loginTable")]
	public partial class loginTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _UserName;
		
		private string _Pass;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPassChanging(string value);
    partial void OnPassChanged();
    #endregion
		
		public loginTable()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pass", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string Pass
		{
			get
			{
				return this._Pass;
			}
			set
			{
				if ((this._Pass != value))
				{
					this.OnPassChanging(value);
					this.SendPropertyChanging();
					this._Pass = value;
					this.SendPropertyChanged("Pass");
					this.OnPassChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NewBook")]
	public partial class NewBook : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _bId;
		
		private string _bName;
		
		private string _bAuthor;
		
		private string _bPubl;
		
		private string _bPurDate;
		
		private string _bPrice;
		
		private long _bQuan;
		
		private EntitySet<IssueReturnBook> _IssueReturnBooks;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnbIdChanging(int value);
    partial void OnbIdChanged();
    partial void OnbNameChanging(string value);
    partial void OnbNameChanged();
    partial void OnbAuthorChanging(string value);
    partial void OnbAuthorChanged();
    partial void OnbPublChanging(string value);
    partial void OnbPublChanged();
    partial void OnbPurDateChanging(string value);
    partial void OnbPurDateChanged();
    partial void OnbPriceChanging(string value);
    partial void OnbPriceChanged();
    partial void OnbQuanChanging(long value);
    partial void OnbQuanChanged();
    #endregion
		
		public NewBook()
		{
			this._IssueReturnBooks = new EntitySet<IssueReturnBook>(new Action<IssueReturnBook>(this.attach_IssueReturnBooks), new Action<IssueReturnBook>(this.detach_IssueReturnBooks));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int bId
		{
			get
			{
				return this._bId;
			}
			set
			{
				if ((this._bId != value))
				{
					this.OnbIdChanging(value);
					this.SendPropertyChanging();
					this._bId = value;
					this.SendPropertyChanged("bId");
					this.OnbIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bName", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string bName
		{
			get
			{
				return this._bName;
			}
			set
			{
				if ((this._bName != value))
				{
					this.OnbNameChanging(value);
					this.SendPropertyChanging();
					this._bName = value;
					this.SendPropertyChanged("bName");
					this.OnbNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bAuthor", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string bAuthor
		{
			get
			{
				return this._bAuthor;
			}
			set
			{
				if ((this._bAuthor != value))
				{
					this.OnbAuthorChanging(value);
					this.SendPropertyChanging();
					this._bAuthor = value;
					this.SendPropertyChanged("bAuthor");
					this.OnbAuthorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bPubl", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string bPubl
		{
			get
			{
				return this._bPubl;
			}
			set
			{
				if ((this._bPubl != value))
				{
					this.OnbPublChanging(value);
					this.SendPropertyChanging();
					this._bPubl = value;
					this.SendPropertyChanged("bPubl");
					this.OnbPublChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bPurDate", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string bPurDate
		{
			get
			{
				return this._bPurDate;
			}
			set
			{
				if ((this._bPurDate != value))
				{
					this.OnbPurDateChanging(value);
					this.SendPropertyChanging();
					this._bPurDate = value;
					this.SendPropertyChanged("bPurDate");
					this.OnbPurDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bPrice", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string bPrice
		{
			get
			{
				return this._bPrice;
			}
			set
			{
				if ((this._bPrice != value))
				{
					this.OnbPriceChanging(value);
					this.SendPropertyChanging();
					this._bPrice = value;
					this.SendPropertyChanged("bPrice");
					this.OnbPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bQuan", DbType="BigInt NOT NULL")]
		public long bQuan
		{
			get
			{
				return this._bQuan;
			}
			set
			{
				if ((this._bQuan != value))
				{
					this.OnbQuanChanging(value);
					this.SendPropertyChanging();
					this._bQuan = value;
					this.SendPropertyChanged("bQuan");
					this.OnbQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NewBook_IssueReturnBook", Storage="_IssueReturnBooks", ThisKey="bId", OtherKey="BookID")]
		public EntitySet<IssueReturnBook> IssueReturnBooks
		{
			get
			{
				return this._IssueReturnBooks;
			}
			set
			{
				this._IssueReturnBooks.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_IssueReturnBooks(IssueReturnBook entity)
		{
			this.SendPropertyChanging();
			entity.NewBook = this;
		}
		
		private void detach_IssueReturnBooks(IssueReturnBook entity)
		{
			this.SendPropertyChanging();
			entity.NewBook = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NewMember")]
	public partial class NewMember : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _mID;
		
		private string _mName;
		
		private string _mContact;
		
		private string _mEmail;
		
		private string _mState;
		
		private string _mCity;
		
		private long _mPinCode;
		
		private System.Data.Linq.Binary _mPhoto;
		
		private string _mPassword;
		
		private string _mPetName;
		
		private EntitySet<IssueReturnBook> _IssueReturnBooks;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmIDChanging(int value);
    partial void OnmIDChanged();
    partial void OnmNameChanging(string value);
    partial void OnmNameChanged();
    partial void OnmContactChanging(string value);
    partial void OnmContactChanged();
    partial void OnmEmailChanging(string value);
    partial void OnmEmailChanged();
    partial void OnmStateChanging(string value);
    partial void OnmStateChanged();
    partial void OnmCityChanging(string value);
    partial void OnmCityChanged();
    partial void OnmPinCodeChanging(long value);
    partial void OnmPinCodeChanged();
    partial void OnmPhotoChanging(System.Data.Linq.Binary value);
    partial void OnmPhotoChanged();
    partial void OnmPasswordChanging(string value);
    partial void OnmPasswordChanged();
    partial void OnmPetNameChanging(string value);
    partial void OnmPetNameChanged();
    #endregion
		
		public NewMember()
		{
			this._IssueReturnBooks = new EntitySet<IssueReturnBook>(new Action<IssueReturnBook>(this.attach_IssueReturnBooks), new Action<IssueReturnBook>(this.detach_IssueReturnBooks));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int mID
		{
			get
			{
				return this._mID;
			}
			set
			{
				if ((this._mID != value))
				{
					this.OnmIDChanging(value);
					this.SendPropertyChanging();
					this._mID = value;
					this.SendPropertyChanged("mID");
					this.OnmIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mName", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string mName
		{
			get
			{
				return this._mName;
			}
			set
			{
				if ((this._mName != value))
				{
					this.OnmNameChanging(value);
					this.SendPropertyChanging();
					this._mName = value;
					this.SendPropertyChanged("mName");
					this.OnmNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mContact", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string mContact
		{
			get
			{
				return this._mContact;
			}
			set
			{
				if ((this._mContact != value))
				{
					this.OnmContactChanging(value);
					this.SendPropertyChanging();
					this._mContact = value;
					this.SendPropertyChanged("mContact");
					this.OnmContactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mEmail", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string mEmail
		{
			get
			{
				return this._mEmail;
			}
			set
			{
				if ((this._mEmail != value))
				{
					this.OnmEmailChanging(value);
					this.SendPropertyChanging();
					this._mEmail = value;
					this.SendPropertyChanged("mEmail");
					this.OnmEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mState", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string mState
		{
			get
			{
				return this._mState;
			}
			set
			{
				if ((this._mState != value))
				{
					this.OnmStateChanging(value);
					this.SendPropertyChanging();
					this._mState = value;
					this.SendPropertyChanged("mState");
					this.OnmStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mCity", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string mCity
		{
			get
			{
				return this._mCity;
			}
			set
			{
				if ((this._mCity != value))
				{
					this.OnmCityChanging(value);
					this.SendPropertyChanging();
					this._mCity = value;
					this.SendPropertyChanged("mCity");
					this.OnmCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mPinCode", DbType="BigInt NOT NULL")]
		public long mPinCode
		{
			get
			{
				return this._mPinCode;
			}
			set
			{
				if ((this._mPinCode != value))
				{
					this.OnmPinCodeChanging(value);
					this.SendPropertyChanging();
					this._mPinCode = value;
					this.SendPropertyChanged("mPinCode");
					this.OnmPinCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mPhoto", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary mPhoto
		{
			get
			{
				return this._mPhoto;
			}
			set
			{
				if ((this._mPhoto != value))
				{
					this.OnmPhotoChanging(value);
					this.SendPropertyChanging();
					this._mPhoto = value;
					this.SendPropertyChanged("mPhoto");
					this.OnmPhotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mPassword", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string mPassword
		{
			get
			{
				return this._mPassword;
			}
			set
			{
				if ((this._mPassword != value))
				{
					this.OnmPasswordChanging(value);
					this.SendPropertyChanging();
					this._mPassword = value;
					this.SendPropertyChanged("mPassword");
					this.OnmPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mPetName", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string mPetName
		{
			get
			{
				return this._mPetName;
			}
			set
			{
				if ((this._mPetName != value))
				{
					this.OnmPetNameChanging(value);
					this.SendPropertyChanging();
					this._mPetName = value;
					this.SendPropertyChanged("mPetName");
					this.OnmPetNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NewMember_IssueReturnBook", Storage="_IssueReturnBooks", ThisKey="mID", OtherKey="MemberID")]
		public EntitySet<IssueReturnBook> IssueReturnBooks
		{
			get
			{
				return this._IssueReturnBooks;
			}
			set
			{
				this._IssueReturnBooks.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_IssueReturnBooks(IssueReturnBook entity)
		{
			this.SendPropertyChanging();
			entity.NewMember = this;
		}
		
		private void detach_IssueReturnBooks(IssueReturnBook entity)
		{
			this.SendPropertyChanging();
			entity.NewMember = null;
		}
	}
}
#pragma warning restore 1591
