//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueReturnBook
    {
        public int ID { get; set; }
        public string EnrollID { get; set; }
        public string Member_Name { get; set; }
        public string Member_Contact { get; set; }
        public string Member_Email { get; set; }
        public string Book_Name { get; set; }
        public string Book_Issue_Date { get; set; }
        public string Book_Return_Date { get; set; }
    }
}
