//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewBook
    {
        public int bId { get; set; }
        public string bName { get; set; }
        public string bAuthor { get; set; }
        public string bPubl { get; set; }
        public string bPurDate { get; set; }
        public string bPrice { get; set; }
        public long bQuan { get; set; }
    }
}
