//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewMember
    {
        public int ID { get; set; }
        public string EnrollID { get; set; }
        public string mName { get; set; }
        public string mContact { get; set; }
        public string mEmail { get; set; }
        public string mState { get; set; }
        public string mCity { get; set; }
        public long mPinCode { get; set; }
        public byte[] mPhoto { get; set; }
        public string mPassword { get; set; }
        public string mPetName { get; set; }
    }
}
